export type AiParticipantStatus = "active" | "inactive";

export type AiParticipant = {
  id: string;
  name: string;
  alias: string;
  provider: string;
  status: AiParticipantStatus;
  emoji: string;
};

export const DEFAULT_AI_PARTICIPANTS: AiParticipant[] = [
  {
    id: "ANTHROPIC_CLAUDE_SONNET_4_5",
    name: "Claude 4.5 Sonnet",
    alias: "claude-sonnet-4-5",
    provider: "Anthropic",
    status: "active",
    emoji: "🤖",
  },
  {
    id: "ANTHROPIC_CLAUDE_OPUS_4_5",
    name: "Claude 4.5 Opus",
    alias: "opus-4-5",
    provider: "Anthropic",
    status: "active",
    emoji: "🟡",
  },
  {
    id: "ANTHROPIC_CLAUDE_SONNET_4",
    name: "Claude Sonnet 4",
    alias: "claude-sonnet-4",
    provider: "Anthropic",
    status: "active",
    emoji: "🤖",
  },
  {
    id: "OPENAI_GPT4O",
    name: "GPT-4o",
    alias: "gpt-4o",
    provider: "OpenAI",
    status: "active",
    emoji: "🧠",
  },
  {
    id: "OPENAI_GPT4_1",
    name: "GPT-4.1",
    alias: "gpt-4.1",
    provider: "OpenAI",
    status: "active",
    emoji: "🧩",
  },
  {
    id: "OPENAI_GPT5_2",
    name: "GPT-5.2",
    alias: "gpt-5.2",
    provider: "OpenAI",
    status: "active",
    emoji: "🌀",
  },
  {
    id: "OPENAI_GPT5",
    name: "GPT-5",
    alias: "gpt-5",
    provider: "OpenAI",
    status: "active",
    emoji: "🚀",
  },
  {
    id: "OPENAI_GPT5_1",
    name: "ChatGPT 5.1",
    alias: "gpt-5.1",
    provider: "OpenAI",
    status: "active",
    emoji: "✨",
  },
  {
    id: "OPENAI_GPT5_1_MINI",
    name: "ChatGPT 5.1 Mini",
    alias: "gpt-5.1-mini",
    provider: "OpenAI",
    status: "active",
    emoji: "⚡",
  },
  {
    id: "OPENAI_O3",
    name: "OpenAI o3",
    alias: "o3",
    provider: "OpenAI",
    status: "active",
    emoji: "🧪",
  },
  {
    id: "OPENAI_O3_MINI",
    name: "OpenAI o3-mini",
    alias: "o3-mini",
    provider: "OpenAI",
    status: "active",
    emoji: "🧮",
  },
  {
    id: "OPENAI_O4_MINI",
    name: "OpenAI o4-mini",
    alias: "o4-mini",
    provider: "OpenAI",
    status: "active",
    emoji: "🛰️",
  },
  {
    id: "OPENAI_GPT35_TURBO",
    name: "GPT-3.5 Turbo",
    alias: "gpt-3-5",
    provider: "OpenAI",
    status: "active",
    emoji: "💡",
  },
  {
    id: "GROK_GROK_3",
    name: "Grok 3",
    alias: "grok",
    provider: "xAI",
    status: "active",
    emoji: "🦾",
  },
  {
    id: "GROK_GROK_3_MINI",
    name: "Grok 3 Mini",
    alias: "grok-3-mini",
    provider: "xAI",
    status: "active",
    emoji: "⚡",
  },
  {
    id: "GROK_GROK_4_0709",
    name: "Grok 4",
    alias: "grok-4",
    provider: "xAI",
    status: "active",
    emoji: "🚀",
  },
  {
    id: "GROK_GROK_4_FAST_NON_REASONING",
    name: "Grok 4 Fast",
    alias: "grok-4-fast",
    provider: "xAI",
    status: "active",
    emoji: "💨",
  },
  {
    id: "GROK_GROK_4_FAST_REASONING",
    name: "Grok 4 Fast Reasoning",
    alias: "grok-4-reasoning",
    provider: "xAI",
    status: "active",
    emoji: "🧠",
  },
  {
    id: "GROK_GROK_4_HEAVY",
    name: "Grok 4 Heavy",
    alias: "grok-4-heavy",
    provider: "xAI",
    status: "active",
    emoji: "🏋️",
  },
  {
    id: "GROK_GROK_CODE_FAST_1",
    name: "Grok Code",
    alias: "grok-code",
    provider: "xAI",
    status: "active",
    emoji: "💻",
  },
  {
    id: "GROK_GROK_2_1212",
    name: "Grok 2",
    alias: "grok-2",
    provider: "xAI",
    status: "active",
    emoji: "✌️",
  },
  {
    id: "GROK_GROK_2_VISION_1212",
    name: "Grok 2 Vision",
    alias: "grok-2-vision",
    provider: "xAI",
    status: "active",
    emoji: "👁️",
  },
  {
    id: "GROK_GROK_2_IMAGE_1212",
    name: "Grok 2 Image",
    alias: "grok-2-image",
    provider: "xAI",
    status: "active",
    emoji: "🖼️",
  },
  {
    id: "GEMINI_GEMINI_PRO",
    name: "Gemini Pro",
    alias: "gemini",
    provider: "Google",
    status: "active",
    emoji: "💎",
  },
  {
    id: "GEMINI_GEMINI_3",
    name: "Gemini 3.0 Pro",
    alias: "gemini-3",
    provider: "Google",
    status: "active",
    emoji: "🔷",
  },
  {
    id: "COHERE_COMMAND_A_03_2025",
    name: "Command A",
    alias: "cohere",
    provider: "Cohere",
    status: "active",
    emoji: "🔮",
  },
  {
    id: "MISTRAL_MISTRAL_LARGE",
    name: "Mistral Large",
    alias: "mistral",
    provider: "Mistral AI",
    status: "active",
    emoji: "🌟",
  },
  {
    id: "DEEPSEEK_DEEPSEEK_CHAT",
    name: "DeepSeek Chat",
    alias: "deepseek",
    provider: "DeepSeek",
    status: "active",
    emoji: "🔍",
  },
  {
    id: "DEEPSEEK_DEEPSEEK_V3",
    name: "DeepSeek V3",
    alias: "deepseek-v3",
    provider: "DeepSeek",
    status: "active",
    emoji: "🧠",
  },
  {
    id: "DEEPSEEK_DEEPSEEK_V3_2",
    name: "DeepSeek V3.2",
    alias: "deepseek-v3.2",
    provider: "DeepSeek",
    status: "active",
    emoji: "🧬",
  },
  {
    id: "KIMI_KIMI_8K",
    name: "Kimi",
    alias: "kimi",
    provider: "Moonshot AI",
    status: "active",
    emoji: "🎯",
  },
  {
    id: "ZAI_ZAI_DEFAULT",
    name: "Z.ai",
    alias: "z.ai",
    provider: "Z.ai",
    status: "active",
    emoji: "⚡",
  },
];
