import type { AiParticipant } from "../types.js";

export const GEMINI_PARTICIPANTS: AiParticipant[] = [
  // Google/Gemini Models - Gems/crystals
  {
    id: "GEMINI_GEMINI_3_5_FLASH",
    name: "Gemini 3.5 Flash",
    alias: "gemini-3.5-flash",
    provider: "Google",
    status: "active",
    emoji: "🔶",
  },
  {
    id: "GEMINI_GEMINI_3_1_PRO",
    name: "Gemini 3.1 Pro",
    alias: "gemini-3.1-pro",
    provider: "Google",
    status: "active",
    emoji: "🔷",
  },
  {
    id: "GEMINI_GEMINI_3_1_FLASH",
    name: "Gemini 3.1 Flash",
    alias: "gemini-3.1-flash",
    provider: "Google",
    status: "active",
    emoji: "💠",
  },
  {
    id: "GEMINI_GEMINI_3_1_FLASH_LITE",
    name: "Gemini 3.1 Flash Lite",
    alias: "gemini-3.1-flash-lite",
    provider: "Google",
    status: "active",
    emoji: "🔸",
  },
  {
    id: "GEMINI_GEMINI_2_5_PRO",
    name: "Gemini 2.5 Pro",
    alias: "gemini-2.5-pro",
    provider: "Google",
    status: "active",
    emoji: "💎",
  },
  {
    id: "GEMINI_GEMINI_2_5_FLASH",
    name: "Gemini 2.5 Flash",
    alias: "gemini-2.5-flash",
    provider: "Google",
    status: "active",
    emoji: "🔹",
  },
  {
    id: "GEMINI_GEMINI_2_5_FLASH_LITE",
    name: "Gemini 2.5 Flash Lite",
    alias: "gemini-2.5-lite",
    provider: "Google",
    status: "active",
    emoji: "✨",
  },
  {
    id: "GEMINI_GEMINI_3_8_FLASH",
    name: "Gemini 3.8 Flash",
    alias: "gemini-3.8-flash",
    provider: "Google",
    status: "active",
    emoji: "🪩",
  },
  {
    id: "GEMINI_GEMINI_3_7_FLASH",
    name: "Gemini 3.7 Flash",
    alias: "gemini-3.7-flash",
    provider: "Google",
    status: "active",
    emoji: "💍",
  },
  {
    id: "GEMINI_GEMINI_3_6_FLASH",
    name: "Gemini 3.6 Flash",
    alias: "gemini-3.6-flash",
    provider: "Google",
    status: "active",
    emoji: "📿",
  },
  {
    id: "GEMINI_GEMINI_3_5_FLASH_LITE",
    name: "Gemini 3.5 Flash Lite",
    alias: "gemini-3.5-flash-lite",
    provider: "Google",
    status: "active",
    emoji: "🪞",
  },
];
