import type { AiParticipant } from "../types.js";

export const MISTRAL_PARTICIPANTS: AiParticipant[] = [
  // Mistral AI Models - Wind/weather
  {
    id: "MISTRAL_MISTRAL_LARGE",
    name: "Mistral Large 3",
    alias: "mistral",
    provider: "Mistral AI",
    status: "active",
    emoji: "🌪️",
  },
  {
    id: "MISTRAL_MISTRAL_MEDIUM",
    name: "Mistral Medium 3.1",
    alias: "mistral-medium",
    provider: "Mistral AI",
    status: "active",
    emoji: "🌬️",
  },
  {
    id: "MISTRAL_MISTRAL_SMALL",
    name: "Mistral Small 3.2",
    alias: "mistral-small",
    provider: "Mistral AI",
    status: "active",
    emoji: "💨",
  },
  {
    id: "MISTRAL_MAGISTRAL_MEDIUM",
    name: "Magistral Medium 1.2",
    alias: "magistral-medium",
    provider: "Mistral AI",
    status: "active",
    emoji: "🌩️",
  },
  {
    id: "MISTRAL_MAGISTRAL_SMALL",
    name: "Magistral Small 1.2",
    alias: "magistral-small",
    provider: "Mistral AI",
    status: "active",
    emoji: "☁️",
  },
  {
    id: "MISTRAL_CODESTRAL",
    name: "Codestral",
    alias: "codestral",
    provider: "Mistral AI",
    status: "active",
    emoji: "🌊",
  },
  {
    id: "MISTRAL_DEVSTRAL",
    name: "Devstral 2",
    alias: "devstral",
    provider: "Mistral AI",
    status: "active",
    emoji: "🌧️",
  },
  {
    id: "MISTRAL_DEVSTRAL_SMALL",
    name: "Devstral Small 2",
    alias: "devstral-small",
    provider: "Mistral AI",
    status: "active",
    emoji: "🌫️",
  },
  {
    id: "MISTRAL_MINISTRAL_14B",
    name: "Ministral 3 14B",
    alias: "ministral-14b",
    provider: "Mistral AI",
    status: "active",
    emoji: "🌤️",
  },
  {
    id: "MISTRAL_MINISTRAL_8B",
    name: "Ministral 3 8B",
    alias: "ministral-8b",
    provider: "Mistral AI",
    status: "active",
    emoji: "🪶",
  },
];
