import type { AiParticipant } from "../types.js";

export const OPENAI_PARTICIPANTS: AiParticipant[] = [
  // OpenAI Models - Space/cosmos
  {
    id: "OPENAI_GPT5_5",
    name: "GPT-5.5",
    alias: "gpt-5.5",
    provider: "OpenAI",
    status: "active",
    emoji: "🌟",
  },
  {
    id: "OPENAI_GPT5_5_PRO",
    name: "GPT-5.5 Pro",
    alias: "gpt-5.5-pro",
    provider: "OpenAI",
    status: "active",
    emoji: "☀️",
  },
  {
    id: "OPENAI_GPT5_2",
    name: "GPT-5.2",
    alias: "gpt-5.2",
    provider: "OpenAI",
    status: "active",
    emoji: "🌀",
  },
  {
    id: "OPENAI_GPT5_2_PRO",
    name: "GPT-5.2 Pro",
    alias: "gpt-5.2-pro",
    provider: "OpenAI",
    status: "active",
    emoji: "🪐",
  },
  {
    id: "OPENAI_GPT5_MINI",
    name: "GPT-5 Mini",
    alias: "gpt-5-mini",
    provider: "OpenAI",
    status: "active",
    emoji: "💫",
  },
  {
    id: "OPENAI_GPT5_NANO",
    name: "GPT-5 Nano",
    alias: "gpt-5-nano",
    provider: "OpenAI",
    status: "active",
    emoji: "✳️",
  },
  {
    id: "OPENAI_GPT4O",
    name: "GPT-4o",
    alias: "gpt-4o",
    provider: "OpenAI",
    status: "active",
    emoji: "🌍",
  },
  {
    id: "OPENAI_GPT4O_MINI",
    name: "GPT-4o mini",
    alias: "gpt-4o-mini",
    provider: "OpenAI",
    status: "active",
    emoji: "🌏",
  },
  {
    id: "OPENAI_GPT4_1",
    name: "GPT-4.1",
    alias: "gpt-4.1",
    provider: "OpenAI",
    status: "active",
    emoji: "🛸",
  },
  {
    id: "OPENAI_GPT4_1_MINI",
    name: "GPT-4.1 mini",
    alias: "gpt-4.1-mini",
    provider: "OpenAI",
    status: "active",
    emoji: "🛰️",
  },
  {
    id: "OPENAI_GPT4_1_NANO",
    name: "GPT-4.1 nano",
    alias: "gpt-4.1-nano",
    provider: "OpenAI",
    status: "active",
    emoji: "🌌",
  },
  {
    id: "OPENAI_O3",
    name: "OpenAI o3",
    alias: "o3",
    provider: "OpenAI",
    status: "active",
    emoji: "🔭",
  },
  {
    id: "OPENAI_O3_PRO",
    name: "OpenAI o3-pro",
    alias: "o3-pro",
    provider: "OpenAI",
    status: "active",
    emoji: "🔮",
  },
  {
    id: "OPENAI_O4_MINI",
    name: "OpenAI o4-mini",
    alias: "o4-mini",
    provider: "OpenAI",
    status: "active",
    emoji: "🌠",
  },
  {
    id: "OPENAI_GPT6_ASTRA",
    name: "GPT-6 Astra",
    alias: "gpt-6-astra",
    provider: "OpenAI",
    status: "active",
    emoji: "🌞",
  },
  // GPT-6 Sol and GPT-6 Luna (below) serve the same tiers at half the price, so the 5.6
  // pair is parked to keep indistinguishable bots out of the room. GPT-5.6 Terra stays:
  // OpenAI shipped no GPT-6 Terra.
  {
    id: "OPENAI_GPT5_6_SOL",
    name: "GPT-5.6 Sol",
    alias: "gpt-5.6-sol",
    provider: "OpenAI",
    status: "inactive",
    emoji: "🌎",
  },
  {
    id: "OPENAI_GPT5_6_TERRA",
    name: "GPT-5.6 Terra",
    alias: "gpt-5.6-terra",
    provider: "OpenAI",
    status: "active",
    emoji: "🌗",
  },
  {
    id: "OPENAI_GPT5_6_LUNA",
    name: "GPT-5.6 Luna",
    alias: "gpt-5.6-luna",
    provider: "OpenAI",
    status: "inactive",
    emoji: "🌙",
  },
  {
    id: "OPENAI_GPT6_SOL",
    name: "GPT-6 Sol",
    alias: "gpt-6-sol",
    provider: "OpenAI",
    status: "active",
    emoji: "☄️",
  },
  {
    id: "OPENAI_GPT6_LUNA",
    name: "GPT-6 Luna",
    alias: "gpt-6-luna",
    provider: "OpenAI",
    status: "active",
    emoji: "🌖",
  },
];
