import type { AiParticipant } from "../types.js";

export const QWEN_PARTICIPANTS: AiParticipant[] = [
  // Qwen/Alibaba Models - East Asian culture
  {
    id: "QWEN_QWEN3_6_MAX_PREVIEW",
    name: "Qwen3.6 Max Preview",
    alias: "qwen3.6-max",
    provider: "Qwen",
    status: "active",
    emoji: "🀄",
  },
  {
    id: "QWEN_QWEN3_MAX",
    name: "Qwen3 Max",
    alias: "qwen3-max",
    provider: "Qwen",
    status: "active",
    emoji: "🐲",
  },
  {
    id: "QWEN_QWEN3_235B",
    name: "Qwen3-235B",
    alias: "qwen3-235b",
    provider: "Qwen",
    status: "active",
    emoji: "🏯",
  },
  {
    id: "QWEN_QWEN3_CODER_PLUS",
    name: "Qwen3 Coder Plus",
    alias: "qwen3-coder-plus",
    provider: "Qwen",
    status: "active",
    emoji: "🧧",
  },
  {
    id: "QWEN_QWEN3_CODER_FLASH",
    name: "Qwen3 Coder Flash",
    alias: "qwen3-coder-flash",
    provider: "Qwen",
    status: "active",
    emoji: "🎎",
  },
  {
    id: "QWEN_QWEN_PLUS",
    name: "Qwen Plus",
    alias: "qwen-plus",
    provider: "Qwen",
    status: "active",
    emoji: "🏮",
  },
  {
    id: "QWEN_QWEN_TURBO",
    name: "Qwen Turbo",
    alias: "qwen-turbo",
    provider: "Qwen",
    status: "active",
    emoji: "🎋",
  },
  {
    id: "QWEN_QWEN_FLASH",
    name: "Qwen Flash",
    alias: "qwen-flash",
    provider: "Qwen",
    status: "active",
    emoji: "🎍",
  },
  {
    id: "QWEN_QWEN3_8_MAX",
    name: "Qwen3.8-Max",
    alias: "qwen3.8-max",
    provider: "Qwen",
    status: "active",
    emoji: "🥮",
  },
  {
    id: "QWEN_QWEN3_7_MAX",
    name: "Qwen3.7-Max",
    alias: "qwen3.7-max",
    provider: "Qwen",
    status: "active",
    emoji: "🧨",
  },
  {
    id: "QWEN_QWEN3_7_PLUS",
    name: "Qwen3.7-Plus",
    alias: "qwen3.7-plus",
    provider: "Qwen",
    status: "active",
    emoji: "🪭",
  },
  {
    id: "QWEN_QWEN3_6_FLASH",
    name: "Qwen3.6-Flash",
    alias: "qwen3.6-flash",
    provider: "Qwen",
    status: "active",
    emoji: "🎏",
  },
  {
    id: "QWEN_QWEN3_8_FLASH",
    name: "Qwen3.8-Flash",
    alias: "qwen3.8-flash",
    provider: "Qwen",
    status: "active",
    emoji: "🎐",
  },
  {
    id: "QWEN_QWEN3_8_OMNI_FLASH",
    name: "Qwen3.8-Omni-Flash",
    alias: "qwen3.8-omni-flash",
    provider: "Qwen",
    status: "active",
    emoji: "🪷",
  },
];
