import type { AiParticipant } from "../types.js";

export const ZAI_PARTICIPANTS: AiParticipant[] = [
  // Z.ai Models - Tools/engineering
  {
    id: "ZAI_ZAI_GLM_5_1",
    name: "GLM-5.1",
    alias: "glm-5.1",
    provider: "Z.ai",
    status: "active",
    emoji: "🏭",
  },
  {
    id: "ZAI_ZAI_GLM_5",
    name: "GLM-5",
    alias: "glm-5",
    provider: "Z.ai",
    status: "active",
    emoji: "🏗️",
  },
  {
    id: "ZAI_ZAI_GLM_4_7",
    name: "GLM-4.7",
    alias: "glm-4.7",
    provider: "Z.ai",
    status: "active",
    emoji: "⚙️",
  },
  {
    id: "ZAI_ZAI_GLM_4_7_FLASH",
    name: "GLM-4.7-Flash",
    alias: "glm-4.7-flash",
    provider: "Z.ai",
    status: "active",
    emoji: "🔧",
  },
  {
    id: "ZAI_ZAI_GLM_4_7V",
    name: "GLM-4.7V",
    alias: "glm-4.7v",
    provider: "Z.ai",
    status: "active",
    emoji: "🛠️",
  },
  {
    id: "ZAI_ZAI_GLM_4_6",
    name: "GLM-4.6",
    alias: "glm-4.6",
    provider: "Z.ai",
    status: "active",
    emoji: "🔩",
  },
  {
    id: "ZAI_ZAI_GLM_4_6V",
    name: "GLM-4.6V",
    alias: "glm-4.6v",
    provider: "Z.ai",
    status: "active",
    emoji: "🪛",
  },
  {
    id: "ZAI_ZAI_GLM_4_5",
    name: "GLM-4.5",
    alias: "glm-4.5",
    provider: "Z.ai",
    status: "active",
    emoji: "🔨",
  },
  {
    id: "ZAI_ZAI_GLM_4_5_AIR",
    name: "GLM-4.5-Air",
    alias: "glm-4.5-air",
    provider: "Z.ai",
    status: "active",
    emoji: "🪚",
  },
  {
    id: "ZAI_ZAI_GLM_4_5_AIRX",
    name: "GLM-4.5-AirX",
    alias: "glm-4.5-airx",
    provider: "Z.ai",
    status: "active",
    emoji: "📐",
  },
  {
    id: "ZAI_ZAI_GLM_4_5_FLASH",
    name: "GLM-4.5-Flash",
    alias: "glm-4.5-flash",
    provider: "Z.ai",
    status: "active",
    emoji: "🧲",
  },
  {
    id: "ZAI_ZAI_GLM_4_5_LONG",
    name: "GLM-4.5-Long",
    alias: "glm-4.5-long",
    provider: "Z.ai",
    status: "active",
    emoji: "📏",
  },
  {
    id: "ZAI_ZAI_DEFAULT",
    name: "Z.ai",
    alias: "z.ai",
    provider: "Z.ai",
    status: "active",
    emoji: "🔆",
  },
  {
    id: "ZAI_ZAI_GLM_5_2",
    name: "GLM-5.2",
    alias: "glm-5.2",
    provider: "Z.ai",
    status: "active",
    emoji: "🔗",
  },
  {
    id: "ZAI_ZAI_GLM_5_3",
    name: "GLM-5.3",
    alias: "glm-5.3",
    provider: "Z.ai",
    status: "active",
    emoji: "🪝",
  },
  {
    id: "ZAI_ZAI_GLM_5_3_FLASH",
    name: "GLM-5.3-Flash",
    alias: "glm-5.3-flash",
    provider: "Z.ai",
    status: "active",
    emoji: "🪓",
  },
  {
    id: "ZAI_ZAI_GLM_5_3_FLASHX",
    name: "GLM-5.3-FlashX",
    alias: "glm-5.3-flashx",
    provider: "Z.ai",
    status: "active",
    emoji: "🧰",
  },
];
